<?php
namespace APP\MVC\V;

class MAP_V {

    public function main($model){
    	$result='';
    	$muassisaho=$model->get_muassisaho();
    	$mks='';
    	$fg=false;
    	foreach ($muassisaho as $key => $v) {
    		if($v['geo_lat']!=''){
    			if($fg) $mks.=",\n";
    			$mks.='[ '.$v['geo_lng'].','.$v['geo_lat'].', "'.$v['name_ru'].'" ]';
    			if(!$fg){$fg=true;}
    		}    		
    	}
    	$mlist='';
    	if(count($muassisaho)>0){
    		$mlist.='<select id="xlist">'."\n";
    			foreach($muassisaho as $k=>$vl){
    				$mlist.='<option value="'.$k.'">'.$vl['name_ru'].'</option>'."\n"; 
    			}
    		$mlist.="</select>\n";    		
    	}
    	\CORE\BC\UI::init()->pos['link'].='<link rel="stylesheet" href="'.UIPATH.'/ext/map/leaflet.css" />';
    	\CORE\BC\UI::init()->pos['js'].='
    	<script src="'.UIPATH.'/ext/map/leaflet.js"></script>
    	<script src="'.UIPATH.'/ext/map/singleclick.js"></script>
		<script language="javascript">

			function SaveCoords(xlat, xlng){
				var xid = $("#xlist").val();
				$.post("./?c=map&act=ajax&do=marker",{ id: xid, lat: xlat, lng: xlng }, function(data){
					if(data=="ok") {
						//alert("Точка добавлена!");
					} else {
						alert(data);
					}
				});
			}

	        function init() {

	            var map = new L.Map(\'map\');

	            L.tileLayer(\'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png\', {
	                attribution: \'&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors\',
	                maxZoom: 17
	            }).addTo(map);

	            map.attributionControl.setPrefix(\'\'); // Dont show the Powered by Leaflet text.

	            var dushanbe = new L.LatLng(38.5495108,68.7781477);
	            map.setView(dushanbe, 12);

	            // Define an array. This could be done in a seperate js file.
	            // This tidy formatted section could even be generated by a server-side script
	            // or fetched seperately as a jsonp request.

	            var markers = [
	                '.$mks.'
	            ];

	            //Loop through the markers array
	            for (var i=0; i<markers.length; i++) {

	                var lon = markers[i][0];
	                var lat = markers[i][1];
	                var popupText = markers[i][2];

	                var markerLocation = new L.LatLng(lat, lon);
	                var marker = new L.Marker(markerLocation);
	                map.addLayer(marker);

	                marker.bindPopup(popupText);

	            }

	            // addMarkerByClick

	            var zmarker = null;

	            map.on("singleclick",function ( e ) {
		                if ($("#xflag").is(":checked")) {
		                		if(zmarker!=null) map.removeLayer(zmarker);
		                    var markerLocation = new L.LatLng(e.latlng.lat, e.latlng.lng);
		                    var xmarker = new L.Marker(markerLocation);
		                    	zmarker = xmarker;
		                    map.addLayer(xmarker);
		                    //console.log( "singleclick", e );
		                    //L.popup().setLatLng( e.latlng )
		                    //    .setContent( "<p><code>singleclick</code> at " + e.latlng )
		                    //    .openOn( map );
		                    //alert(e.latlng.lat + \' : \' + e.latlng.lng);
		                    SaveCoords(e.latlng.lat, e.latlng.lng);
		                }
		            } );
		        
	        }

	        $(document).ready(function() {

	        	init();

			});
	    </script>
    	';
    	$result.='<div id="map" style="height: 540px"></div>
    	<div id="mysidebar">
    		<div id="xsidebar" class="xmg">'.$mlist.' <input type="checkbox" id="xflag"> 
    		<label for="xflag">edit</label>
    		</div>
    	</div>
    	';
		return $result;
    }


}