<?php
namespace APP\MVC\V;

class MAP_V {

    public function main($model){
    	$result='';
    	$muassisaho=$model->get_muassisaho();
    	$mks='';
    	foreach ($muassisaho as $key => $v) {
    		if($v['geo_lat']!=''){
    			$mks.='[ '.$v['geo_lat'].','.$v['geo_lng'].', "'.$v['name_ru'].'" ],'."\n";
    		}    		
    	}
    	$mlist='';
    	if(count($muassisaho)>0){
    		$mlist.='<select id="xlist">'."\n";
    			foreach($muassisaho as $k=>$vl){
    				$mlist.='<option value="'.$k.'">'.$vl['name_ru'].'</option>'."\n"; 
    			}
    		$mlist.="</select>\n";    		
    	}
    	\CORE\BC\UI::init()->pos['link'].='<link rel="stylesheet" href="'.UIPATH.'/ext/map/leaflet.css" />';
    	\CORE\BC\UI::init()->pos['js'].='
    	<script src="'.UIPATH.'/ext/map/leaflet.js"></script>
    	<script src="'.UIPATH.'/ext/map/singleclick.js"></script>
		<script language="javascript">

			function SaveCoords(){

		            				
			}

	        function init() {
	            var map = new L.Map(\'map\');

	            L.tileLayer(\'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png\', {
	                attribution: \'&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors\',
	                maxZoom: 17
	            }).addTo(map);
	            map.attributionControl.setPrefix(\'\'); // Dont show the Powered by Leaflet text.

	            var dushanbe = new L.LatLng(38.5495108,68.7781477);
	            map.setView(dushanbe, 12);

	            var xmarkers = new L.FeatureGroup();

	            // Define an array. This could be done in a seperate js file.
	            // This tidy formatted section could even be generated by a server-side script
	            // or fetched seperately as a jsonp request.
	            var markers = [
	                '.$mks.'
	            ];

	            /*
	            	[ 68.780057,38.579006, "Флаги баландтарин дар Осиё" ],
	                [ 68.785250,38.583032, "Хонаи ман" ],
	                [ 68.787267, 38.584701, \'Биё чойхурива бача<br><a href="https://en.wikipedia.org/wiki/Nelsons_Column">wp</a><br/><img src="http://agroinform.tj/informers/prices/generate.php" alt="Рыночные цены Таджикистана"  />\' ]
	            */

	            //Loop through the markers array
	            for (var i=0; i<markers.length; i++) {

	                var lon = markers[i][0];
	                var lat = markers[i][1];
	                var popupText = markers[i][2];

	                var markerLocation = new L.LatLng(lat, lon);
	                var marker = new L.Marker(markerLocation);
	                map.addLayer(marker);

	                marker.bindPopup(popupText);

	            }

	            // test

	            map.on("singleclick",function ( e ) {
		                if ($("#xflag").is(":checked")) {
		                	map.removeLayer(markers);
		                    var markerLocation = new L.LatLng(e.latlng.lat, e.latlng.lng);
		                    var marker = new L.Marker(markerLocation);
		                    map.addLayer(marker);
		                    //console.log( "singleclick", e );
		                    //L.popup().setLatLng( e.latlng )
		                    //    .setContent( "<p><code>singleclick</code> at " + e.latlng )
		                    //    .openOn( map );
		                    // alert(e.latlng.lat + \' : \' + e.latlng.lng);
		                    SaveCoords(e.latlng.lat,e.latlng.lng);
		                }
		            } );
		        
	        }

	        $(document).ready(function() {

	        	init();

			});
	    </script>
    	';
    	$result.='<div id="map" style="height: 540px"></div>
    	<div id="mysidebar">
    		<div id="xsidebar" class="xmg">'.$mlist.' <input type="checkbox" id="xflag"> 
    		<label for="xflag">edit</label>
    		</div>
    	</div>
    	';
		return $result;
    }


}